/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    DownloadMusic: typeof import('./views/Music/components/downloadMusic/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Main: typeof import('./views/Main.vue')['default']
    MainPanel: typeof import('./views/MainPanel/index.vue')['default']
    MainWindow: typeof import('./views/MainWindow.vue')['default']
    Music: typeof import('./views/Music/index.vue')['default']
    MusicDetail: typeof import('./views/Music/components/MusicDetail/index.vue')['default']
    Ribbon: typeof import('./views/Ribbon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchMusic: typeof import('./views/Music/components/SearchMusic/index.vue')['default']
    Video: typeof import('./views/Video/index.vue')['default']
  }
}
