/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./App.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Main: typeof import('./views/Main.vue')['default']
    MainWindow: typeof import('./views/MainWindow.vue')['default']
    Ribbon: typeof import('./views/Ribbon/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
